export const ActionTypes = {
    FECTH_PRODUCTS: "FECTH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  };